Rosey/markdown-draft-js

src/draft-to-markdown.js

Offset wasn't being properly calculated so multiple entities in a single block
would not get closed properly.

Fix entities not always closing correctly

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

Example of something that would fail:
**bold text _with italic inside_** _that continues after bold doesn't_
This should be rendered as:
```markdown
**bold text _with italic inside_** _that continues after bold doesn't_
```
But instead is being rendered as
```
**bold text _with italic inside** that continues after bold doesn't_
```
------------------------
This change keeps track of currently open inline styles and close/reopens them
before and after a parent style is closed. GH issue:
https://github.com/Rosey/markdown-draft-js/issues/2

Fix nested inline styles not being correctly closed/reopened

---

src/draft-to-markdown.js

This is an "issue" with markdown - `**a **` is not properly rendered, whereas
`**a** ` is.
So, for example,  in cases when the final few chars in a bold block are spaces,
remove them and then re-add _after_ we close off the bold block.
We do this with all the inline styles 🙃

Move trailing whitespace to _after_ closing tags

---

src/draft-to-markdown.js

Switching because of issues with emoji when using slice,
https://mathiasbynens.be/notes/javascript-unicode talks about this a bit.

Switch to `Array.from` instead of `slice`

---

src/draft-to-markdown.js
src/markdown-to-draft.js
test/draft-to-markdown.spec.js
test/markdown-to-draft.spec.js

[RawDraftContentBlock can have data](https://github.com/facebook/draft-js/blob/master/src/model/encoding/RawDraftContentBlock.js#L30).
[medium-draft](https://github.com/brijeshb42/medium-draft) uses blocks for images so I need to access the block data (and a crazy remarkable block rule to get images as blocks).
But there also seem to be some other use cases for block data, for example a code block with params.

add block data support

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

There was some code in place for this but it wasn't working in all
cases. For inline styles like italic and bold, markdown doesn't play
nice when the final few characters are whitepsace, so this checks for
that and cuts it out, adds the closing markdown character, and _then_
re-adds the trailing whitespace.
----
⭐️  Note: I'm going to have to add another PR to handle a related-but-different case that can happen: Leading WS. Markdown is equally unhappy with something like `** Test**`  but this current PR only checks for `**Test **`

Fix bugginess when converting draftjs trailing whitespace to markdown

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

Because markdown doesn't work when there's leading whitespace we need to
trim it off the front.
Approach here is to hang on to styles to add and not actually add them
until we hit a non-whitespace character.

Fix bug with draft-to-markdown leading whitespace

---

src/draft-to-markdown.js

This is an additional fix on top of https://github.com/Rosey/markdown-draft-js/pull/3.
Rich text
**_bold/italic_** plain
Expected markdown
`**_bold/italic_** plain`
Actual markdown
`**_bold/italic_**__ plain`

Fix reopening of inline styles

---

README.md
src/draft-to-markdown.js
src/markdown-to-draft.js
test/draft-to-markdown.spec.js
test/idempotency.spec.js
test/markdown-to-draft.spec.js

This is an option that can be turned on if you want 1:1 parity with
draftjs as far as newlines go.
By default, markdown's rules state that multiple newlines are collapsed.
With this option turned on, when converting back and forth, they will NOT be.
However, it's worth noting that if you then decide to pass the  markdown
to a 3rd party to render it into HTML, unless that 3rd party's parser
has a similar option, the newlines will be collapsed at that point.
https://github.com/Rosey/markdown-draft-js/issues/37

Fix markdown stripping blank paragraphs/newlines

---

src/markdown-to-draft.js
test/idempotency.spec.js
test/markdown-to-draft.spec.js

Before this - markdown with nested styles couldn't be properly rendered.
Before this - the last tag would always be assumed as the closing tag, so if there's more than 1 open tag, the logic would fail, the logic now checks for two things to assume a closing tag:
- if the closing tag matches the opening tag.
- if the length of the item is 0.
----
Original PR: https://github.com/Rosey/markdown-draft-js/pull/42
Issue: https://github.com/Rosey/markdown-draft-js/issues/43

Fix closing tags

---

src/markdown-to-draft.js
test/draft-to-markdown.spec.js
test/markdown-to-draft.spec.js

See #47 for backstory.
This version uses the much simpler `Array.from` implementation to solve issues with restoring markdown styles when the markdown contains emojis.

Fix handling of emoji

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js
test/idempotency.spec.js

Won't work for more complex markdown, like if you include link code in
your draft copy, but in that case I suspect you know markdown and expect
it to convert anyway.
But this will escape all the normies, like \* and \_.
Reason being someone may actually want those characters to appear as-is
if they're typing them into their draft editor.
There's a TODO in the comment to look into some of the more complicated
cases but tbh I just am too sleep deprived and busy to think about an
elegant and proper fix I am sorry 😬 I think for many people this will
be sufficient.
----
🙃 🙃 🙃 🙃 🙃 🙃 🙃 🙃 🙃 🙃 
https://github.com/Rosey/markdown-draft-js/issues/52
Very sorry for tapping out on the more complicated cases here, hoping this will tide people over until I'm not a total zombie.

Escape markdown characters when converting from draft to markdown

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

https://github.com/Rosey/markdown-draft-js/pull/62 + an additional commit for `preserveNewLines`
There's some problems with `markdownToDraft` as outlined in https://github.com/Rosey/markdown-draft-js/issues/59 and with this change there will be additional work needed there when doing the bug fix. This idempotency test should pass, but fails:
```js
it('renders formatted new lines text correctly', function () {
var markdownString = '> Test\n\n\n> Hello There\n> \n> \n\nSmile\n\n\n\n\n\n\n\nYep Hi';
var draftJSObject = markdownToDraft(markdownString, {preserveNewlines: true});
var markdownFromDraft = draftToMarkdown(draftJSObject, {preserveNewlines: true});
expect(markdownFromDraft).toEqual(markdownString);
});
```

Dont style empty blocks

---

src/markdown-to-draft.js
test/markdown-to-draft.spec.js

Only the last item in a multi line blockquote was being reflected in
markdown to draft, due to a flaw in the `depth` check.
Consider this parsed remarkable data:
```
blockquote_open
paragraph_open
inline "Hello"
paragraph_close
paragraph_open
inline "Hi there"
paragraph_close
blockquote_close
```
draft conversion should be
blockquote -> hello
blockquote -> hi there
but instead was simply
blockquote -> hi there
because we were ignoring nested block styles and overwriting the text
content of the first blockquote with the `inline`.
This fixes by cloning whatever current block we are in if necessary.
---
https://github.com/Rosey/markdown-draft-js/issues/63

Fix issue of multiline blockquotes having content stripped

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

Headings and blockquotes should only be escaped if they're at the
beginning of a line.
https://github.com/Rosey/markdown-draft-js/issues/61

Update markdown character escape logic

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

`>` and `#` don’t need to be escaped if they aren’t immediately followed
by a whitespace character.

Further fixes to markdown escape logic on draftToMarkdown

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

I noticed that @mixxt and @dino115 forked this repo and added this bug
fix which is 👍 so I’ve ripped it off to make sure the bug is fixed
here too 🙃

Don’t escape markdown characters in draftToMarkdown if inside code

---

src/draft-to-markdown.js

The backslash is correct when not in code. Need special treatment
applied still when inside code or codeblock.

Add backtic escaping when not in code/codeblock

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

This wasn’t a huge priority for me to start with because most markdown
parsers seem to handle this for you anyway, but in the interest of
fixing what seems like a weird behaviour, I have fixed it.
Now, draft-to-markdown ordered lists no longer do:
1. Item one
1. Item two
1. Item three
They do
1. Item one
2. Item two
3. Item three
... and all is happy in the world :)

Update draft-to-markdown ordered list conversion to use right numbers

---

src/markdown-to-draft.js
test/markdown-to-draft.spec.js

DraftJS doesn’t support tables (at least not out of the box) and if we
have them turned on in markdown it creates missing blocks of text where
the table content is.
Since someone could theoretically write a DraftJS plugin to support
tables (in fact I think there is one already!) We may want to make this
an option to turn on at some point so people can write their own
entityhandler for tables in markdownToDraft/draftToMarkdown, but I
wasn’t sure what the best API for that would be so it’s just a hardcoded
value for now.

Disable tables when converting markdown to draft

---

src/draft-to-markdown.js
src/markdown-to-draft.js
test/draft-to-markdown.spec.js
test/markdown-to-draft.spec.js

in draft.js’s link example they use `URL` for link entities which is
what this lib was using as well, however I’ve come across some plugins
which use `href` instead, which seems like a resonable value as well.
Soooo I have added support for both values. If a user wants some other
way more custom value that doesn’t make sense I might suggest they
define their own BlockEntity and pass it in as an option (see the
README).

Add support for href to links

---

README.md
src/draft-to-markdown.js
test/draft-to-markdown.spec.js

This PR adds an option to prevent escaping special markdown characters (i.e `\*|_|~|\\|`) when converting from draft to markdown.
```js
draftToMarkdown(draftObject, {
preserveMarkdown: true,
})
```
When `preserveMarkdown` is set to `true` the generated markdown string will be in its "raw" form, with no escaped characters. This feature is useful, in the case where saving markdown to a database is desired. 
The code changes in this PR are meant to be backwards compatible with the existing API. So the `draftToMarkdown` function will behave as normal when the `preserveMarkdown` flag is not set.
Let me know if you have any questions or concerns about these code changes.
p.s. Thanks for creating this awesome library!!:) It's been lifesaver!
Run the test suite to ensure all tests pass
```
npm …
```

Add preserveMarkdown option

---

README.md
src/markdown-to-draft.js
test/markdown-to-draft.spec.js

When using Remarkable directly, we we can pass two arguments to its constructor - the first is the template and the second is an object with additional options.
markdown-draft-js only lets us pass a single value to the `remarkableOptions`, so we need to choose whether to use a preset or an options object.
This PR makes it possible to pass both (in an array).

Add support for passing preset with additional options to Remarkable

---

src/markdown-to-draft.js
test/markdown-to-draft.spec.js

Closes #87 
As it was pointed out in the issue itself, the support for hardbreaks was missing.

Support hardbreaks

---

src/markdown-to-draft.js
test/markdown-to-draft.spec.js

When converting markdown to Draft.js raw object using remarkable, support the
`'hr'` block type given by remarkable, and allow the user to pass an option
`blockTypes` containing a `hr` key telling markdown-to-draft which block type
to use.
see #96

Add support for hr in markdown-to-draft

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

🤮 I hate how crazy this got but maybe it's not as bad as I think...
Basically we were seeing an issue where when a user pasted a link in, the "markdown" characters were being escaped, even though they were not actually valid markdown characters because they weren't in the right context.
Like _ is a markdown character, but if there's no matching closing character, it doesn't need to be escaped.
Similarily, when a markdown character is like this: h_a_h it shouldn't be escaped because markdown dictates there needs to be whitespace.
I was hoping this issue wasn't a big deal and wanted to ignore it, but the issue with the links was too big to ignore.

Make markdown escaping in draft-to-markdown much smarter

---

README.md
src/markdown-to-draft.js
test/markdown-to-draft.spec.js

Hello Rosey,
after asking you a while ago in #91 about the possibility to disable single rules I finally got around to check it out and found that it's not yet possible but already marked with a todo comment in the code.
This pull request allows users to add `enable` and `disable` options to the `remarkableOptions` object, like so:
```javascript
var rawDraftJSObject = markdownToDraft(markdownString, {
remarkablePreset: 'commonmark',
remarkableOptions: {
disable: {
inline: ['links', 'emphasis'],
block: ['heading']
},
enable: {
block: 'table',
core: ['abbr']
}
}
});
```
I saw that tables are disabled by default and kept that setting, unless the user enables them.
I have extended the Readme and tests appropriately, i hope they are easy enough to understand.
My added code is formatted with …

Add option to enable or disable remarkable rules

---

.babelrc
.gitignore
package.json
src/draft-to-markdown.js
src/index.js
src/markdown-to-draft.js

This is useful for bundlers like rollup which does not handle commonjs
out of the box.

Add esm entry point support

---

src/draft-to-markdown.js
src/markdown-to-draft.js
test/idempotency.spec.js

This should fix the issue discussed here:
https://github.com/Rosey/markdown-draft-js/issues/59
Newlines were not working as expected after styled blocks

Added double newline after styled line

---

package-lock.json
package.json
src/markdown-to-draft.js

Ref https://github.com/jonschlinkert/remarkable/releases/tag/v2.0.0
A few highlightes
- esm support
- public api uses named exports
- autolinker is available as a separate entry point
- smaller browser bundle with dropped entities list
[It's twice smaller now](https://bundlephobia.com/result?p=remarkable@2.0.0)

Migrate to remarkable v2

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js
test/idempotency.spec.js

A fairly edge case bug fix around soft newlines within block quotes... and identified another bug and wrote a test for it but not yet fixed as I got a bit stuck 🙂 Will come back to it in another PR.

Preserve newlines draft

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

Draft sometimes includes trailing whitespace in bold/italic/etc text, which markdown can't handle.
We had code in place to handle tabs and spaces but not newlines. Bug wasn't surfaced initially since out of the box draft generally always creates new paragraphs instead of a soft newline. However, there are ways you can insert a soft newline so this case can happen.

Fix inline styling with trailing newlines

---

README.md

I wanted to add another helpful usage example to your README. It's another way that people can quickly learn how to use your **wonderful** library! 
This example is long enough to show exactly how to integrate with draft-js but short enough to not show anything unnecessary. 
This improvement was inspired by [draftjs-md-converter](https://github.com/kadikraman/draftjs-md-converter). I found their usage example most helpful, it saved me a lot of time, and I wanted you to have one too.
Thanks! ❤

Improve README with a longer yet concise usage example

---

README.md

Just fixing a couple of links in the documentation to use DraftJS's new home.

Fix a couple of broken links in README.md

---

src/draft-to-markdown.js
test/draft-to-markdown.spec.js

Hello @Rosey 👋 ! Thank you for this handy library. It works quite well for me, except for a little issue with the way overlapping ranges of inline styles and entity ranges are handled.
The conversion breaks for the following example Draft.js input:
[foo **bar**](http://localhost:8000) **baz**
Raw state:
```
{
blocks: [
{
key: '5rq8m',
text: 'foo bar baz',
type: 'unstyled',
depth: 0,
inlineStyleRanges: [{ offset: 4, length: 7, style: 'BOLD' }],
entityRanges: [{ offset: 0, length: 7, key: 0 }],
data: {}
}
],
entityMap: {
'0': {
type: 'LINK',
mutability: 'MUTABLE',
data: {
url: 'http://localhost:8000',
}
}
}
}
```
_markdown-draft-js_ maps it to:
```
[foo **bar](http://localhost:3000/g/statics/jm/journeys/ckcexvump0004wv6ze8ujmo9w) baz**
```
⚠️ This is invalid markdown.
This PR adjust the …

Fix problems with overlapping formats

---

src/draft-to-markdown.js

Fix the number of ordered lists when there is unstyled block between the lists
Example:
Header
1. Some list
2. Some list
Header
1. Some list
2. Some list
will be converted to
Header
1. Some list
2. Some list
Header
3. Some list
4. Some list

Fix the number of ordered lists

---

src/markdown-to-draft.js
test/draft-to-markdown.spec.js
test/markdown-to-draft.spec.js

https://github.com/Rosey/markdown-draft-js/issues/156
Adding support for creating DraftJS inline style for strikethrough.
Adding tests for conversion of strikethrough to and from markdown.

ISSUE 156: Strikethrough conversion is incomplete

---

src/markdown-to-draft.js
test/idempotency.spec.js

Found an issue in my editor after sending form (serialize->deseriaize)
newlines after lists are increased.

Render preserved new lines after list correctly

---

README.md

I found the documentation ambiguous because it referred to "newlines" which could be either an empty line in the text or the newline character, and one empty line requires two newline characters.  I have slightly adjusted it to be more clear about what it is trying to say.
Potentially closes out https://github.com/Rosey/markdown-draft-js/issues/142

Clarify documentation about the collapsing of multiple empty lines
